### ISSUE TITLE
IllegalArgumentException: max_edge_cases < 0

### ISSUE THREAD

**Issue by dmivankov** [jlink/jqwik#180]
## Testing Problem

When maxEdgeCases reaches 0 (too many edge cases?), IllegalArgumentException may be triggered in generating cases due to "default" edge cases

https://github.com/jlink/jqwik/blob/cc952102e3209a20c63e9b1cb6a7c3007a028b91/engine/src/main/java/net/jqwik/engine/properties/arbitraries/DefaultStringArbitrary.java#L42
https://github.com/jlink/jqwik/blob/cc952102e3209a20c63e9b1cb6a7c3007a028b91/engine/src/main/java/net/jqwik/engine/properties/arbitraries/MultivalueArbitraryBase.java#L84

Not very clear how to fix
- on edge case exhaustion don't generate 0/1-length cases
- always generate 0/1 cases, but fix `effectiveMaxEdgeCases` to be at least `0`
- treat limit<0 as 0 in places like https://github.com/jlink/jqwik/blob/cc952102e3209a20c63e9b1cb6a7c3007a028b91/engine/src/main/java/net/jqwik/engine/properties/arbitraries/IntegralGeneratingArbitrary.java#L59

Sorry for not adding repro case, can try to add it later

**Comment by jlink** [comment]
> Sorry for not adding repro case, can try to add it later

Yes please. Would be most interesting to see how those situations come to happen. There's probably a missing edge case (pun intended) I didn't think about during implementation.

**Comment by dmivankov** [comment]
Stacktrace
```
	at java.base/java.util.stream.ReferencePipeline.limit(ReferencePipeline.java:469)
	at net.jqwik.engine.properties.arbitraries.IntegralGeneratingArbitrary.edgeCases(IntegralGeneratingArbitrary.java:59)
	at net.jqwik.engine.properties.arbitraries.DefaultByteArbitrary.edgeCases(DefaultByteArbitrary.java:33)
	at net.jqwik.engine.properties.arbitraries.MultivalueArbitraryBase.fixedSizeEdgeCases(MultivalueArbitraryBase.java:107) // this one receives maxEdgeCases = -1, ones below have 0
	at net.jqwik.engine.properties.arbitraries.MultivalueArbitraryBase.edgeCases(MultivalueArbitraryBase.java:86)
	at net.jqwik.engine.properties.arbitraries.DefaultListArbitrary.edgeCases(DefaultListArbitrary.java:41)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$3.edgeCases(ArbitraryFacadeImpl.java:121)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.facades.CombinatorsFacadeImpl.combineEdgeCases(CombinatorsFacadeImpl.java:52)
	at net.jqwik.api.Combinators$Combinator2$1.edgeCases(Combinators.java:283)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.properties.arbitraries.MultivalueArbitraryBase.fixedSizeEdgeCases(MultivalueArbitraryBase.java:107) // this one also has maxEdgeCases = 0
	at net.jqwik.engine.properties.arbitraries.MultivalueArbitraryBase.edgeCases(MultivalueArbitraryBase.java:86) // here and below maxEdgeCases = 1
	at net.jqwik.engine.properties.arbitraries.DefaultListArbitrary.edgeCases(DefaultListArbitrary.java:41)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$3.edgeCases(ArbitraryFacadeImpl.java:121)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.facades.CombinatorsFacadeImpl.combineEdgeCases(CombinatorsFacadeImpl.java:52)
	at net.jqwik.api.Combinators$Combinator2$1.edgeCases(Combinators.java:283)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.lambda$flatMapArbitrary$19(EdgeCasesSupport.java:152)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.flatMapArbitrary(EdgeCasesSupport.java:166)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$3.edgeCases(ArbitraryFacadeImpl.java:121)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.facades.CombinatorsFacadeImpl.combineEdgeCases(CombinatorsFacadeImpl.java:52)
	at net.jqwik.api.Combinators$Combinator2$1.edgeCases(Combinators.java:283)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.lambda$flatMapArbitrary$19(EdgeCasesSupport.java:152)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.flatMapArbitrary(EdgeCasesSupport.java:166)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$3.edgeCases(ArbitraryFacadeImpl.java:121)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.facades.CombinatorsFacadeImpl.combineEdgeCases(CombinatorsFacadeImpl.java:52)
	at net.jqwik.api.Combinators$Combinator2$1.edgeCases(Combinators.java:283)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.lambda$flatMapArbitrary$19(EdgeCasesSupport.java:152)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.flatMapArbitrary(EdgeCasesSupport.java:166)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$3.edgeCases(ArbitraryFacadeImpl.java:121)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.facades.CombinatorsFacadeImpl.combineEdgeCases(CombinatorsFacadeImpl.java:52)
	at net.jqwik.api.Combinators$Combinator2$1.edgeCases(Combinators.java:283)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.edgeCases(ArbitraryFacadeImpl.java:95)
	at net.jqwik.engine.properties.RandomizedShrinkablesGenerator.lambda$resolveEdgeCases$3(RandomizedShrinkablesGenerator.java:124)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.jqwik.engine.properties.RandomizedShrinkablesGenerator.resolveEdgeCases(RandomizedShrinkablesGenerator.java:125)
	at net.jqwik.engine.properties.RandomizedShrinkablesGenerator.listOfEdgeCases(RandomizedShrinkablesGenerator.java:91)
	at net.jqwik.engine.properties.RandomizedShrinkablesGenerator.forParameters(RandomizedShrinkablesGenerator.java:26)
	at net.jqwik.engine.execution.CheckedProperty.createRandomizedShrinkablesGenerator(CheckedProperty.java:235)
	at net.jqwik.engine.execution.CheckedProperty.createDefaultShrinkablesGenerator(CheckedProperty.java:175)
	at net.jqwik.engine.execution.CheckedProperty.createShrinkablesGenerator(CheckedProperty.java:165)
	at net.jqwik.engine.execution.CheckedProperty.createGenericProperty(CheckedProperty.java:144)
	at net.jqwik.engine.execution.CheckedProperty.check(CheckedProperty.java:67)
	at net.jqwik.engine.execution.PropertyMethodExecutor.executeProperty(PropertyMethodExecutor.java:124)
	at net.jqwik.engine.execution.PropertyMethodExecutor.executeMethod(PropertyMethodExecutor.java:108)
	at net.jqwik.engine.execution.PropertyMethodExecutor.lambda$executePropertyMethod$0(PropertyMethodExecutor.java:88)
	at net.jqwik.api.lifecycle.AroundPropertyHook.lambda$static$0(AroundPropertyHook.java:44)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at net.jqwik.engine.hooks.lifecycle.PropertyLifecycleMethodsHook.aroundProperty(PropertyLifecycleMethodsHook.java:57)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at net.jqwik.engine.hooks.statistics.StatisticsHook.aroundProperty(StatisticsHook.java:32)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at net.jqwik.engine.hooks.lifecycle.AutoCloseableHook.aroundProperty(AutoCloseableHook.java:13)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at net.jqwik.engine.execution.PropertyMethodExecutor.executePropertyMethod(PropertyMethodExecutor.java:86)
	at net.jqwik.engine.execution.PropertyMethodExecutor.execute(PropertyMethodExecutor.java:42)
	at net.jqwik.engine.execution.PropertyTaskCreator.executeTestMethod(PropertyTaskCreator.java:129)
	at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$1(PropertyTaskCreator.java:55)
	at net.jqwik.engine.execution.pipeline.ExecutionTask$1.lambda$execute$0(ExecutionTask.java:31)
	at net.jqwik.engine.execution.lifecycle.CurrentTestDescriptor.runWithDescriptor(CurrentTestDescriptor.java:25)
	at net.jqwik.engine.execution.pipeline.ExecutionTask$1.execute(ExecutionTask.java:31)
	at net.jqwik.engine.execution.pipeline.ExecutionPipeline.runToTermination(ExecutionPipeline.java:82)
	at net.jqwik.engine.execution.JqwikExecutor.execute(JqwikExecutor.java:46)
	at net.jqwik.engine.JqwikTestEngine.executeTests(JqwikTestEngine.java:70)
	at net.jqwik.engine.JqwikTestEngine.execute(JqwikTestEngine.java:53)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:66)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:58)
	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:58)
	at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:95)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:73)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:50)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:43)
	at com.flexport.bazeljunit5.BazelJUnit5ConsoleLauncher.main(BazelJUnit5ConsoleLauncher.java:60)
```

**Comment by dmivankov** [comment]
Caught one
```java
package com.cognite.copy_to_postgres;

import java.util.stream.Collectors;
import java.util.stream.IntStream;

import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.Combinators;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;

public class UtilsTest {
  @Property
  void testEdgeCases(@ForAll("edgeCases") Object arg1,
      @ForAll("edgeCases") Object arg2) { // 2 args are required for repro
  }

  @Provide("edgeCases")
  Arbitrary<Object> generate() {
    return
        Combinators.withBuilder(Object::new)
            .use(Arbitraries.strings()
                .edgeCases(c -> c.add(IntStream.range(0, 1000) // generate lots of edge cases
                    .mapToObj(String::valueOf)
                    .collect(Collectors.toList())
                    .toArray(String[]::new))))
            .in((a, b) -> a)
            .use(Arbitraries.bytes().list().list()) // single list() gets max edge cases down to 0, list().list() reaches -1
            .in((a, b) -> a)
        .build();
  }
}
```
will try to make a PR

**Comment by jlink** [comment]
@dmivankov Thank you. I’ll have a look at it.

**Comment by dmivankov** [comment]
```diff
diff --git a/engine/src/main/java/net/jqwik/engine/properties/arbitraries/DefaultStringArbitrary.java b/engine/src/main/java/net/jqwik/engine/properties/arbitraries/DefaultStringArbitrary.java
index a74acd87d..3e65fbdbf 100644
--- a/engine/src/main/java/net/jqwik/engine/properties/arbitraries/DefaultStringArbitrary.java
+++ b/engine/src/main/java/net/jqwik/engine/properties/arbitraries/DefaultStringArbitrary.java
@@ -37,7 +37,7 @@ public class DefaultStringArbitrary extends TypedCloneable implements StringArbi
        @Override
        public EdgeCases<String> edgeCases(int maxEdgeCases) {
                EdgeCases<String> emptyStringEdgeCases =
-                               hasEmptyStringEdgeCase() ? emptyStringEdgeCase() : EdgeCases.none();
+                               hasEmptyStringEdgeCase() && maxEdgeCases > 0 ? emptyStringEdgeCase() : EdgeCases.none();
 
                int effectiveMaxEdgeCases = maxEdgeCases - emptyStringEdgeCases.size();
                EdgeCases<String> singleCharEdgeCases =
diff --git a/engine/src/main/java/net/jqwik/engine/properties/arbitraries/MultivalueArbitraryBase.java b/engine/src/main/java/net/jqwik/engine/properties/arbitraries/MultivalueArbitraryBase.java
index f16589337..c82452ff2 100644
--- a/engine/src/main/java/net/jqwik/engine/properties/arbitraries/MultivalueArbitraryBase.java
+++ b/engine/src/main/java/net/jqwik/engine/properties/arbitraries/MultivalueArbitraryBase.java
@@ -79,7 +79,7 @@ abstract class MultivalueArbitraryBase<T, U> extends TypedCloneable implements S
                        BiFunction<List<Shrinkable<T>>, Integer, Shrinkable<C>> shrinkableCreator,
                        int maxEdgeCases
        ) {
-               EdgeCases<C> emptyListEdgeCase = (minSize == 0) ? emptyListEdgeCase(shrinkableCreator) : EdgeCases.none();
+               EdgeCases<C> emptyListEdgeCase = (minSize == 0 && maxEdgeCases > 0) ? emptyListEdgeCase(shrinkableCreator) : EdgeCases.none();
 
                int effectiveMaxEdgeCases = maxEdgeCases - emptyListEdgeCase.size();
                EdgeCases<C> singleElementEdgeCases = (minSize <= 1 && maxSize >= 1)
```
looks sensible - effectiveMaxEdgeCases=0 is probably taken care of by generic code, and minSize==0 case with maxEdgeCases==0 also shouldn't produce cases

**Comment by jlink** [comment]
In the end there were a few more cases in which this bug could show up.

Fixed it in https://github.com/jlink/jqwik/commit/e220e788732c71da08e275ef9c903781dc1bc5a2

Released in 1.5.2-SNAPSHOT

**Comment by ScottG489** [comment]
In case anyone is interested in a simple repro I just came across this issue (I'm still on `1.5.1`):

```
public class DockerAdapterListVolumesTest {
    @Property(tries = 1)
    void foo(@ForAll("bar") List<String> bar) {
    }

    @Provide
    ListArbitrary<String> bar() {
        return Arbitraries.strings().list();
    }
}
```

Any tries > 2 worked fine. Haven't been able to test this against the SNAPSHOT, but it looks like the same issue so it's probably fixed.

**Comment by ScottG489** [comment]
In case anyone is interested in a simple repro I just came across this issue (I'm still on `1.5.1`):

```
public class Foo {
    @Property(tries = 1)
    void foo(@ForAll("bar") List<String> bar) {
    }

    @Provide
    ListArbitrary<String> bar() {
        return Arbitraries.strings().list();
    }
}
```

Any tries > 2 worked fine. Haven't been able to test this against the SNAPSHOT, but it looks like the same issue so it's probably fixed.

**Comment by jlink** [comment]
@ScottG489 Checked your example on 1.5.2-SNAPSHOT and it works fine.
