### ISSUE TITLE
ConcurrentModificationException after test failure

### ISSUE THREAD

**Issue by osi** [jlink/jqwik#210]
I received the following exception after a failing test. It is intermittent.

jqwik 1.5.3, jqwik-spring 0.8.0

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.jqwik.engine.execution.lifecycle.StoreRepository.finishScope(StoreRepository.java:95)
	at net.jqwik.engine.execution.PropertyMethodExecutor.executePropertyMethod(PropertyMethodExecutor.java:98)
	at net.jqwik.engine.execution.PropertyMethodExecutor.execute(PropertyMethodExecutor.java:42)
	at net.jqwik.engine.execution.PropertyTaskCreator.executeTestMethod(PropertyTaskCreator.java:129)
	at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$1(PropertyTaskCreator.java:55)
	at net.jqwik.engine.execution.pipeline.ExecutionTask$1.lambda$execute$0(ExecutionTask.java:31)
	at net.jqwik.engine.execution.lifecycle.CurrentTestDescriptor.runWithDescriptor(CurrentTestDescriptor.java:25)
	at net.jqwik.engine.execution.pipeline.ExecutionTask$1.execute(ExecutionTask.java:31)
	at net.jqwik.engine.execution.pipeline.ExecutionPipeline.runToTermination(ExecutionPipeline.java:82)
	at net.jqwik.engine.execution.JqwikExecutor.execute(JqwikExecutor.java:46)
	at net.jqwik.engine.JqwikTestEngine.executeTests(JqwikTestEngine.java:70)
	at net.jqwik.engine.JqwikTestEngine.execute(JqwikTestEngine.java:53)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by jlink** [comment]
Do you have a way to reproduce it?
I could put in some safe-guards but they might effect performance so I'm still hesitating w/o being able to prove they are useful.

**Comment by osi** [comment]
I'm unable to consistently reproduce it. It happened twice yesterday when running tests. I'll keep an eye on it as it occurs to see if I can find patterns. My initial goal in raising the issue here is in case others also observe this and have additional data.

**Comment by osi** [comment]
I was able to reproduce this in my test suite when I had a test that failed, and _also_ when shrinking failed,
```
n.j.e.p.s.PropertyShrinker               : Shrinking timeout reached after 10 seconds.
  You can switch on full shrinking with '@Property(shrinking = ShrinkingMode.FULL)'
```

... Disabling shrinking appears to have alleviated the issue.

**Comment by jlink** [comment]
I deployed a preliminary fix to 1.5.4-SNAPSHOT. Maybe you'll find the time to try it...

**Comment by osi** [comment]
Is the snapshot published anywhere?

**Comment by jlink** [comment]
@osi Should be on https://oss.sonatype.org/content/repositories/snapshots/. Unless I screwed up.

**Comment by osi** [comment]
ah, gotcha. i had to add that to my Gradle configuration.

that fix make the exception go away in the scenario i had.

**Comment by jlink** [comment]
I’m not really happy with the solution so I’ll leave the issue open for a while.

**Comment by jlink** [comment]
No new ideas :-( So I’ll close it.
