### ISSUE TITLE
OutsideJqwikException on simple test case after 1.5.0+ upgrade

### ISSUE THREAD

**Issue by moon-golfer** [jlink/jqwik#266]
## Testing Problem

I wrote the following sample code and run it on intelliJ and kept getting the same exception on v1.5.0+.
The same code works fine on 1.4.0 and lower...

This is the sample code I reduced my actual test code down to:
```
import java.util.Random;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.Combinators;

public class Test {

    public static Arbitrary<String> testing() {
        return Combinators.withBuilder(StringBuilder::new)
            .use(Arbitraries.of("123")).in(StringBuilder::append)
            .build(StringBuilder::toString);
    }

    @org.junit.jupiter.api.Test
    public void test() {
        long seed = 1242352352;
        testing().generator(0).next(new Random(seed)).value();
    }
}
```

Stacktrace:
```
net.jqwik.engine.execution.lifecycle.OutsideJqwikException: The current action must be run on a jqwik thread, i.e. container, property or hook.
Maybe you spawned off a thread?

	at net.jqwik.engine.execution.lifecycle.CurrentTestDescriptor.get(CurrentTestDescriptor.java:50)
	at net.jqwik.engine.facades.StoreFacadeImpl.get(StoreFacadeImpl.java:24)
	at net.jqwik.api.lifecycle.Store.get(Store.java:92)
	at net.jqwik.api.lifecycle.Store.getOrCreate(Store.java:68)
	at net.jqwik.engine.facades.Memoize.generatorStore(Memoize.java:13)
	at net.jqwik.engine.facades.Memoize.memoizedGenerator(Memoize.java:26)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl.memoizedGenerator(ArbitraryFacadeImpl.java:221)
	at net.jqwik.api.Arbitrary.generator(Arbitrary.java:92)
	at net.jqwik.api.Combinators$Combinator2$1.rawGenerator(Combinators.java:264)
	at net.jqwik.api.Combinators$Combinator2$1.generator(Combinators.java:255)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$2.generator(ArbitraryFacadeImpl.java:79)
	at com.test.my.code.project.Test.test(Test.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


Process finished with exit code 255

```

- Removing the ` .use(Arbitraries.of("123")).in(StringBuilder::append)` will make the test pass, so the exception is coming from the generate(int).
- Changing to .example or marking with @Example seems to also help as well, but I dont think I need to do that given that is a new issue after upgrading.
- I also turned off parallel junit testing so test are running on the main thread (although it was not a problem with 1.4.0) and still getting the same error.

**Comment by jlink** [comment]
Using generators in the way you do is no longer supported. Instead, you have to use: `Arbitrary.sample()` or `Arbitrary.sampleStream()`:

```java
@org.junit.jupiter.api.Test
public void test() {
	testing().sample();
}
```

The reason is that efficiently generating values requires quite some statefule machinery under the hood.
You should read https://jqwik.net/docs/current/user-guide.html#using-arbitraries-directly and especially https://jqwik.net/docs/current/user-guide.html#using-arbitraries-outside-jqwik-lifecycle for more guidance.

Moreover, use at least version 1.5.6 or - even better - the most recent 1.6.1.

`Combinators.withBuilder` has been deprecated; the replacement is `Buildes.withBuilder`:

```java
public static Arbitrary<String> testing() {
	return Builders.withBuilder(StringBuilder::new)
				   .use(Arbitraries.of("123")).in(StringBuilder::append)
				   .build(StringBuilder::toString);
}
```

Feel free to reopen the issue if any more questions show up.

**Comment by moon-golfer** [comment]
Thanks for the reply. A side question, how can we supply a seed now with the new sample workflow like before?
My seed is calculated based on the function input parameter like so:

For example:
```
public static Arbitrary<String> testing() {
        return Combinators.withBuilder(StringBuilder::new)
            .use(Arbitraries.of("123")).in(StringBuilder::append)
            .build(StringBuilder::toString);
}

public static generate(String data) {
   long seed = 1294253 % data.length(); 
   // Original --- return testing().generate(0).next(new Random(seed)).value();
   return testing().sample();
}

@Test
public void test() {
   assertThat(generate("testing")).equals("...");
}
```

**Comment by jlink** [comment]
There's currently no official way to provide a seed for sampling. If there was one, it should be part of `JqwikSession`. 

What are you using the seed for? If you need to control the seed why not use `@Property` or `@Example` in the first place? 

If you can convince me that sampling with explicit seed is needed, a new issue for this feature is welcome.

**Comment by moon-golfer** [comment]
I have multiple test that will call with the arbitrary to generate some custom object dynamically given a settings object. Then, it will take some fields from the settings object to calculate a seed to make sure the same setting or different settings object with those same fields (string and numbers) will generate the same outcome. 

Now with samples, based on your comment this is not supported. How can I supply a seed dynamically with @Propery or @Example? I see that it's possible to supply data with @FromData with @Property, but that does not seem to apply to seed.

**Comment by jlink** [comment]
Your previous approach with using the generator directly still works __within a property method or when using `JqwikSession`__. For example the following code should run alright (in 1.6.x):

```java
@org.junit.jupiter.api.Test
public void test() {
	JqwikSession.run(() -> {
		testing().generator(1000).next(new Random(42L));
	});
}
```

I just doubt that this is the best approach. But I haven't properly understood your use case.
