### ISSUE TITLE
can jqwik not tolerate other, non-jqwik parameters?

### ISSUE THREAD

**Issue by androidfred** [jlink/jqwik#317]
## Testing Problem

```kotlin
    //given pre-existing test like this
    @Test
    fun patch_email_200(pups: PupsDbFixture) {
      //...
    }
    
//where pups parameter is resolved by
class PupsDbFixtureParameterResolver : ParameterResolver {
    override fun supportsParameter(
        parameterContext: ParameterContext?,
        extensionContext: ExtensionContext?
    ): Boolean {
        return parameterContext?.parameter?.type == PupsDbFixture::class.java
    }

    override fun resolveParameter(
        parameterContext: ParameterContext?,
        extensionContext: ExtensionContext?
    ): PupsDbFixture? {
        return extensionContext?.getStore(
            ExtensionContext.Namespace.create(extensionContext.requiredTestClass.simpleName)
        )?.get("pupsDbFixture", PupsDbFixture::class.java)
    }
}

//and afaik the pups parameter can not be removed

//i want to turn it into a property test like
    @Property
    fun patch_email_200(
        pups: PupsDbFixture,
        @ForAll @Email email: String
    ) {
      //...
    }

//but getting error
//    Parameter [com.expedia.www.pc.user.profiles.service.fixture.PupsDbFixture pups] cannot be resolved:
//	No matching resolver could be found
//net.jqwik.api.lifecycle.CannotResolveParameterException: Parameter [com.expedia.www.pc.user.profiles.service.fixture.PupsDbFixture pups] cannot be resolved:
//	No matching resolver could be found
//	at net.jqwik.engine.execution.ResolvingParametersGenerator.lambda$findResolvableParameter$0(ResolvingParametersGenerator.java:70)
//	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
//	at net.jqwik.engine.execution.ResolvingParametersGenerator.findResolvableParameter(ResolvingParametersGenerator.java:68)
//	at net.jqwik.engine.execution.ResolvingParametersGenerator.next(ResolvingParametersGenerator.java:43)
//	at net.jqwik.engine.properties.GenericProperty.check(GenericProperty.java:57)
//	at net.jqwik.engine.execution.CheckedProperty.check(CheckedProperty.java:67)
//	at net.jqwik.engine.execution.PropertyMethodExecutor.executeProperty(PropertyMethodExecutor.java:90)
//	at net.jqwik.engine.execution.PropertyMethodExecutor.executeMethod(PropertyMethodExecutor.java:69)
//	at net.jqwik.engine.execution.PropertyMethodExecutor.lambda$execute$0(PropertyMethodExecutor.java:49)
//	at net.jqwik.api.lifecycle.AroundPropertyHook.lambda$static$0(AroundPropertyHook.java:46)
//	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
//	at net.jqwik.engine.hooks.lifecycle.PropertyLifecycleMethodsHook.aroundProperty(PropertyLifecycleMethodsHook.java:57)
//	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
//	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
//	at net.jqwik.engine.hooks.statistics.StatisticsHook.aroundProperty(StatisticsHook.java:37)
//	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
//	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
//	at net.jqwik.engine.hooks.lifecycle.AutoCloseableHook.aroundProperty(AutoCloseableHook.java:13)
//	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
//	at net.jqwik.engine.execution.PropertyMethodExecutor.execute(PropertyMethodExecutor.java:47)
//	at net.jqwik.engine.execution.PropertyTaskCreator.executeTestMethod(PropertyTaskCreator.java:166)
//	at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$1(PropertyTaskCreator.java:51)
//	at net.jqwik.engine.execution.lifecycle.CurrentDomainContext.runWithContext(CurrentDomainContext.java:28)
//	at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$2(PropertyTaskCreator.java:50)
//	at net.jqwik.engine.execution.pipeline.ExecutionTask$1.lambda$execute$0(ExecutionTask.java:31)
//	at net.jqwik.engine.execution.lifecycle.CurrentTestDescriptor.runWithDescriptor(CurrentTestDescriptor.java:17)
//	at net.jqwik.engine.execution.pipeline.ExecutionTask$1.execute(ExecutionTask.java:31)
//	at net.jqwik.engine.execution.pipeline.ExecutionPipeline.runToTermination(ExecutionPipeline.java:82)
//	at net.jqwik.engine.execution.JqwikExecutor.execute(JqwikExecutor.java:46)
//	at net.jqwik.engine.JqwikTestEngine.executeTests(JqwikTestEngine.java:70)
//	at net.jqwik.engine.JqwikTestEngine.execute(JqwikTestEngine.java:53)
//	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
//	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
//	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
//	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
//	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
//	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
//	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
//	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
//	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
//	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
//	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
//	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
//	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
//	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
//	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
//	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
//	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
//	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
//	at com.sun.proxy.$Proxy2.stop(Unknown Source)
//	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
//	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
//	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
//	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
//	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
//	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
//	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
//	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
//	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
//	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
//	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
//	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
//	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
//	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
//	at java.base/java.lang.Thread.run(Thread.java:829)
```

is there no way to enable jqwik to tolerate other, non-jqwik parameters?

## Suggested Solution
I don't have a suggested solution, just a question

## Discussion
I don't have a suggested solution, just a question

**Comment by jlink** [comment]
You’re mixing two things that cannot be mixed: a jqwik property and a Jupiter parameter resolver. Jupiter and jqwik are seperate test engines that come with their own lifecycle, and their own lifecycle hooks. The solution to your problem is to use jqwik‘s [ResolveParameterHook](https://jqwik.net/docs/current/user-guide.html#other-hooks) instead of `ParameterResolver`.

**Comment by androidfred** [comment]
Right, I did see the hooks but was hoping I was missing something as it's unlikely that will refactoring to turn them into ResolveParameterHook is appropriate for this particular codebase of ours. No worries, understood, thanks for the response to what was probably a dumb question from a newbie :)

**Comment by jlink** [comment]
> Right, I did see the hooks but was hoping I was missing something as it's unlikely that will refactoring to turn them into ResolveParameterHook is appropriate for this particular codebase of ours. No worries, understood, thanks for the response to what was probably a dumb question from a newbie :)

You don't have to refactor them, duplicating would suffice. If you don't rely too  much on `ExtensionContext` having a common parent class that does the bulk of the work is often quite simple. I've done that a few times.
