### ISSUE TITLE
equals and hashCode methods for Arbitraries vs Memoize.memoizedGenerator

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#339]
`Memoize.memoizedGenerator(Arbitrary<U> arbitrary, ...` seems to expect well-defined `equals` and `hashCode`.

However, many jqwik arbitraries use default hashCode and equals since they are fined via anonymous classes (e.g. `Arbitrarires.just`, combine, flatMap, etc).

Does it make sense to move the implementation to top-level classes and override `equals`, `hashCode` accordingly?

Note: it looks like `map`/`flatMap` should use map function in the hashCode/equals, so equality for lambdas would almost always fail :-/

**Comment by jlink** [comment]
The same anonymous class instance would still provide the same hashCode and be equal to itself, so this is covered.
Having the same filter with different lambdas is supposed to produce different generators, so this is the desired effect.

This leaves cases where the exact same arbitrary definition, e.g. `Arbitraries.just("a")` is used more than once in a single property. This is probably rather rare except for recursive arbitrary definitions. 

Is the optimisation worth it? I don't really know. Have you run into cases like this?

**Comment by vlsi** [comment]
> The same anonymous class instance would still provide the same hashCode and be equal to itself, so this is covered

I believe that does not look like that.
By default, anonymous classes do not implement hashCode, so they are never equal to one another. They keep the default `Object#hashCode` and `Object#equals` which means objects produced by anonymous classes are never equal.

That means any arbitrary becomes effectively uncacheable after `net.jqwik.engine.facades.ArbitraryFacadeImpl#map` no matter what.

> This leaves cases where the exact same arbitrary definition, e.g. Arbitraries.just("a") is used more than once in a single property

If you expect that generator for `Arbitraries.just` should not be cacheable, then why have the cache in the first place?
In my experiment, the cache within `Memoize.memoizeGenerator` is the top CPU and Heap consumer (see https://github.com/jlink/jqwik/issues/347)

That is why I suggest the cache should be reworked to support reusing the values or removed altogether.

**Comment by jlink** [comment]
> I believe that does not look like that.
> By default, anonymous classes do not implement hashCode, so they are never equal to one another. They keep the default `Object#hashCode` and `Object#equals` which means objects produced by anonymous classes are never equal.

My point was that the same _instance_ of the anonymous class will be equal to itself.

> If you expect that generator for Arbitraries.just should not be cacheable, then why have the cache in the first place?
> In my experiment, the cache within Memoize.memoizeGenerator is the top CPU and Heap consumer (see https://github.com/jlink/jqwik/issues/347)

The reason I introduced memoization for generators is that previously they were created freshly for each try. This could be _very_ slow in some cases. But maybe there's a better way to tackle that problem than caching _all_ generators. I'd have to deep-dive into jqwik code history for refreshing my memory on the details.

**Comment by jlink** [comment]
@vlsi Could you try branch https://github.com/jlink/jqwik/tree/simplified-memoization to check if memory usage of memorization cache is going down in your cases? Also if you notice any difference in performance?

In this branch I only use memoization for top-level arbitraries, which is the case it was made for in the first place.

**Comment by vlsi** [comment]
Is there a way to capture metrics like generated properties/sec?

I remember you do not like dependencies, however something for metrics might help (hdrhistogram? Micrometer?)

**Comment by vlsi** [comment]
I can try, however, I expect that all my top-level Arbitrary depend on state, so their generators are not easily cacheable

**Comment by jlink** [comment]
At least it should not get worse.

Von meinem iPhone gesendet

**Comment by vlsi** [comment]
It looks like `simplified-memoization` is worse as I have the following:

```kotlin
val arbitraryColumnName = combine(
    Arbitraries.chars().range('A', 'Z'),
    Arbitraries.strings().withCharRange('A', 'Z').withCharRange('0', '9')
        .withChars('#', '$', '_', ' ')
        .ofMinLength(0).ofMaxLength(29)
) { first, rest -> first + rest }
```

I did intentionally cache it into a field, so I reuse the same Arbitrary instance for the naming in a hope that jqwik would cache it.
Now jqwik creates the generator for the naming again and again with stacktraces like

```
"Test worker" #1 prio=5 os_prio=31 cpu=14591.54ms elapsed=15.87s tid=0x0000000147014e00 nid=0x2603 runnable  [0x000000016d29a000]
   java.lang.Thread.State: RUNNABLE
	at java.math.BigInteger.valueOf(java.base@17.0.1/BigInteger.java:1194)
	at net.jqwik.engine.properties.arbitraries.randomized.RandomGenerators.integers(RandomGenerators.java:49)
	at net.jqwik.engine.properties.arbitraries.randomized.RandomGenerators.chars(RandomGenerators.java:45)
	at net.jqwik.engine.properties.arbitraries.CharacterRangeArbitrary.generator(CharacterRangeArbitrary.java:24)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl.generator(ArbitraryFacadeImpl.java:238)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl.memoizedGenerator(ArbitraryFacadeImpl.java:228)
	at net.jqwik.api.Arbitrary.generator(Arbitrary.java:92)
	at net.jqwik.engine.properties.shrinking.FlatMappedShrinkable.lambda$new$0(FlatMappedShrinkable.java:25)
	at net.jqwik.engine.properties.shrinking.FlatMappedShrinkable$$Lambda$722/0x0000000800fcab38.apply(Unknown Source)

...


"Test worker" #1 prio=5 os_prio=31 cpu=116907.10ms elapsed=121.56s tid=0x0000000147014e00 nid=0x2603 runnable  [0x000000016d299000]
   java.lang.Thread.State: RUNNABLE
	at java.math.BigInteger.compareMagnitude(java.base@17.0.1/BigInteger.java:3820)
	at java.math.BigInteger.compareTo(java.base@17.0.1/BigInteger.java:3795)
	at java.math.BigInteger.compareTo(java.base@17.0.1/BigInteger.java:132)
	at net.jqwik.engine.properties.Range.includes(Range.java:38)
	at net.jqwik.engine.properties.arbitraries.randomized.RandomIntegralGenerators.checkTargetInRange(RandomIntegralGenerators.java:41)
	at net.jqwik.engine.properties.arbitraries.randomized.RandomIntegralGenerators.bigIntegers(RandomIntegralGenerators.java:21)
	at net.jqwik.engine.properties.arbitraries.randomized.RandomGenerators.bigIntegers(RandomGenerators.java:65)
	at net.jqwik.engine.properties.arbitraries.randomized.RandomGenerators.integers(RandomGenerators.java:51)
	at net.jqwik.engine.properties.arbitraries.randomized.RandomGenerators.chars(RandomGenerators.java:45)
	at net.jqwik.engine.properties.arbitraries.CharacterRangeArbitrary.generator(CharacterRangeArbitrary.java:24)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl.generator(ArbitraryFacadeImpl.java:238)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl.memoizedGenerator(ArbitraryFacadeImpl.java:228)
	at net.jqwik.api.Arbitrary.generator(Arbitrary.java:92)
	at net.jqwik.engine.properties.shrinking.FlatMappedShrinkable.lambda$new$0(FlatMappedShrinkable.java:25)
	at net.jqwik.engine.properties.shrinking.FlatMappedShrinkable$$Lambda$722/0x0000000800fcab38.apply(Unknown Source)
	at net.jqwik.engine.properties.shrinking.FlatMappedShrinkable.lambda$new$1(FlatMappedShrinkable.java:30)
	at net.jqwik.engine.properties.shrinking.FlatMappedShrinkable$$Lambda$723/0x0000000800fcad80.apply(Unknown Source)
	at net.jqwik.engine.properties.shrinking.FlatMappedShrinkable.generateShrinkable(FlatMappedShrinkable.java:39)
	at net.jqwik.engine.properties.shrinking.FlatMappedShrinkable.shrinkable(FlatMappedShrinkable.java:83)
	at net.jqwik.engine.properties.shrinking.FlatMappedShrinkable.value(FlatMappedShrinkable.java:79)
	at net.jqwik.engine.properties.shrinking.ShrinkableContainer$$Lambda$709/0x0000000800fc6490.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(java.base@17.0.1/ReferencePipeline.java:197)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@17.0.1/ArrayList.java:1625)
	at java.util.stream.AbstractPipeline.copyInto(java.base@17.0.1/AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@17.0.1/AbstractPipeline.java:499)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@17.0.1/ReduceOps.java:921)
	at java.util.stream.AbstractPipeline.evaluate(java.base@17.0.1/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(java.base@17.0.1/ReferencePipeline.java:682)
	at net.jqwik.engine.properties.shrinking.ShrinkableContainer.createValue(ShrinkableContainer.java:29)
	at net.jqwik.engine.properties.shrinking.ShrinkableContainer.value(ShrinkableContainer.java:34)
	at net.jqwik.engine.properties.shrinking.ShrinkableString.value(ShrinkableString.java:10)
	at net.jqwik.engine.properties.shrinking.CombinedShrinkable$$Lambda$616/0x0000000800fa7008.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(java.base@17.0.1/ReferencePipeline.java:197)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@17.0.1/ArrayList.java:1625)
	at java.util.stream.AbstractPipeline.copyInto(java.base@17.0.1/AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@17.0.1/AbstractPipeline.java:499)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@17.0.1/ReduceOps.java:921)
	at java.util.stream.AbstractPipeline.evaluate(java.base@17.0.1/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(java.base@17.0.1/ReferencePipeline.java:682)
	at net.jqwik.engine.properties.shrinking.CombinedShrinkable.createValues(CombinedShrinkable.java:29)
	at net.jqwik.engine.properties.shrinking.CombinedShrinkable.createValue(CombinedShrinkable.java:25)
	at net.jqwik.engine.properties.shrinking.CombinedShrinkable.value(CombinedShrinkable.java:21)
	at net.jqwik.engine.properties.shrinking.ShrinkableContainer$$Lambda$709/0x0000000800fc6490.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(java.base@17.0.1/ReferencePipeline.java:197)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@17.0.1/ArrayList.java:1625)
	at java.util.stream.AbstractPipeline.copyInto(java.base@17.0.1/AbstractPipeline.java:509)
```

**Comment by jlink** [comment]
How is arbitraryColumnName being used in a property? That’s the point that should be memoized, so I wonder why it isn’t.

**Comment by vlsi** [comment]
I generate one of`jqwik.api.state.Action` via

```kotlin
combine(
    arbitraryColumnName.set().ofMinSize(1).ofMaxSize(1000).flatMapEach { _, u ->
        `add column`(just(u), MultiplicityFilter.SINGLE)
    },
    otherIngredients,
) { ... -> mixingThemUntilItLooksLike_state_Arbitrary }
```

What I want to achieve is to add "up to 1000" columns, and the column names have to be unique, so I use `.set().flatMapEach`. No idea if there's a better way of doing it.

On the other hand, I like how I can reuse the same `add column` generator on its own

**Comment by vlsi** [comment]
I see that I can cache `arbitraryColumnName.set().ofMinSize(1).ofMaxSize(1000)` as yet another arbitrary, however, it looks like `combine` would still be treated as the top-level arbitrary, so the generator for my "1000 names" would still be recomputed if you cache top-level arbitrary only.

**Comment by jlink** [comment]
I think I now understand why the generators are recreated each time, but that should also have been the case in main branch. Are you sure the behaviour is new in `simplified-memoization`?

**Comment by vlsi** [comment]
On the main branch, wrapping generators are re-created, however, arbitraryColumnName generator is shared.
Will double-check the branch, however, I am quite sure I tested with simplified-memoization

**Comment by jlink** [comment]
I hopefully caught all arbitrary implementations. Happy about feedback as for memory usage and speed.

**Comment by vlsi** [comment]
Thank you. You caught me in the middle of another refactoring, so I'll test this a bit later.
