### ISSUE TITLE
Transitively generating UUIDs fails

### ISSUE THREAD

**Issue by tmohme** [jlink/jqwik#382]
## Testing Problem

Clearly, it _is_ possible to generate UUIDs with jqwik by writing a corresponding ArbitraryProvider, which I have done and successfully use.
Nevertheless, I ran into a problem when I tried to generate instances of a class `MyClass` that contains a UUID with `@ForAll @UseType MyClass myClass`.

The problem is, that jqwik didn't choose my `UuidArbitraryProvider`, but decided to use reflection to invoke a `UUID.fromString(...)` factory method with a String argument, which failed with an Exception because the random String fed into the method obviously didn't meet its requirements.
The initial `IllegalArgumentException` then got swallowed and rethrown by `net.jqwik.engine.properties.arbitraries.DefaultTraverseArbitrary#generateNext` as `GenerationError`.
Eventually I got a `TooManyFilterMissesException` from `net.jqwik.engine.properties.arbitraries.randomized.IgnoreExceptionGenerator#nextUntilAccepted`.
Unfortunately, the message logged for this exception does not indicate the actual reason the for the failure:

```
net.jqwik.engine.properties.arbitraries.randomized.IgnoreExceptionGenerator@3bd08435 missed more than 10000 times.
net.jqwik.api.TooManyFilterMissesException: net.jqwik.engine.properties.arbitraries.randomized.IgnoreExceptionGenerator@3bd08435 missed more than 10000 times.
	at app//net.jqwik.engine.properties.arbitraries.randomized.IgnoreExceptionGenerator.lambda$nextUntilAccepted$2(IgnoreExceptionGenerator.java:43)
	at app//net.jqwik.engine.properties.MaxTriesLoop.loop(MaxTriesLoop.java:25)
	at app//net.jqwik.engine.properties.arbitraries.randomized.IgnoreExceptionGenerator.nextUntilAccepted(IgnoreExceptionGenerator.java:26)
	at app//net.jqwik.engine.properties.arbitraries.randomized.IgnoreExceptionGenerator.next(IgnoreExceptionGenerator.java:22)
	at app//net.jqwik.engine.properties.shrinking.FlatMappedShrinkable.lambda$new$1(FlatMappedShrinkable.java:30)
	at app//net.jqwik.engine.properties.shrinking.FlatMappedShrinkable.generateShrinkable(FlatMappedShrinkable.java:39)
	at app//net.jqwik.engine.properties.shrinking.FlatMappedShrinkable.shrinkable(FlatMappedShrinkable.java:83)
	at app//net.jqwik.engine.properties.shrinking.FlatMappedShrinkable.value(FlatMappedShrinkable.java:79)
	at java.base@11.0.15/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base@11.0.15/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.15/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.15/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at app//net.jqwik.engine.properties.shrinking.CombinedShrinkable.createValues(CombinedShrinkable.java:29)
	at app//net.jqwik.engine.properties.shrinking.CombinedShrinkable.createValue(CombinedShrinkable.java:25)
	at app//net.jqwik.engine.properties.shrinking.CombinedShrinkable.value(CombinedShrinkable.java:21)
	at app//net.jqwik.engine.properties.arbitraries.randomized.IgnoreExceptionGenerator.lambda$nextUntilAccepted$1(IgnoreExceptionGenerator.java:32)
	at app//net.jqwik.engine.properties.MaxTriesLoop.loop(MaxTriesLoop.java:19)
	at app//net.jqwik.engine.properties.arbitraries.randomized.IgnoreExceptionGenerator.nextUntilAccepted(IgnoreExceptionGenerator.java:26)
	at app//net.jqwik.engine.properties.arbitraries.randomized.IgnoreExceptionGenerator.next(IgnoreExceptionGenerator.java:22)
	at app//net.jqwik.engine.properties.arbitraries.randomized.WithEdgeCasesGenerator.next(WithEdgeCasesGenerator.java:26)
	at app//net.jqwik.engine.properties.RandomizedParameterGenerator.next(RandomizedParameterGenerator.java:25)
	at app//net.jqwik.engine.properties.PurelyRandomShrinkablesGenerator.lambda$generateNext$0(PurelyRandomShrinkablesGenerator.java:21)
	at java.base@11.0.15/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base@11.0.15/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.15/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.15/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at app//net.jqwik.engine.properties.PurelyRandomShrinkablesGenerator.generateNext(PurelyRandomShrinkablesGenerator.java:22)
	at app//net.jqwik.engine.properties.RandomizedShrinkablesGenerator.next(RandomizedShrinkablesGenerator.java:212)
	at app//net.jqwik.engine.properties.RandomizedShrinkablesGenerator.next(RandomizedShrinkablesGenerator.java:15)
	at app//net.jqwik.engine.execution.ResolvingParametersGenerator.next(ResolvingParametersGenerator.java:36)
	at app//net.jqwik.engine.execution.AfterFailureParametersGenerator.next(AfterFailureParametersGenerator.java:85)
	at app//net.jqwik.engine.properties.GenericProperty.check(GenericProperty.java:57)
	at app//net.jqwik.engine.execution.CheckedProperty.check(CheckedProperty.java:67)
	at app//net.jqwik.engine.execution.PropertyMethodExecutor.executeProperty(PropertyMethodExecutor.java:90)
	at app//net.jqwik.engine.execution.PropertyMethodExecutor.executeMethod(PropertyMethodExecutor.java:69)
	at app//net.jqwik.engine.execution.PropertyMethodExecutor.lambda$execute$0(PropertyMethodExecutor.java:49)
	at app//net.jqwik.api.lifecycle.AroundPropertyHook.lambda$static$0(AroundPropertyHook.java:46)
	at app//net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at app//net.jqwik.api.PropertyDefaults$PropertyDefaultsHook.aroundProperty(PropertyDefaults.java:91)
	at app//net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at app//net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at app//net.jqwik.engine.hooks.lifecycle.PropertyLifecycleMethodsHook.aroundProperty(PropertyLifecycleMethodsHook.java:57)
	at app//net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at app//net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at app//net.jqwik.engine.hooks.statistics.StatisticsHook.aroundProperty(StatisticsHook.java:37)
	at app//net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at app//net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at app//net.jqwik.engine.hooks.lifecycle.AutoCloseableHook.aroundProperty(AutoCloseableHook.java:13)
	at app//net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at app//net.jqwik.engine.execution.PropertyMethodExecutor.execute(PropertyMethodExecutor.java:47)
	at app//net.jqwik.engine.execution.PropertyTaskCreator.executeTestMethod(PropertyTaskCreator.java:166)
	at app//net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$1(PropertyTaskCreator.java:51)
	at app//net.jqwik.engine.execution.lifecycle.CurrentDomainContext.runWithContext(CurrentDomainContext.java:28)
	at app//net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$2(PropertyTaskCreator.java:50)
	at app//net.jqwik.engine.execution.pipeline.ExecutionTask$1.lambda$execute$0(ExecutionTask.java:31)
	at app//net.jqwik.engine.execution.lifecycle.CurrentTestDescriptor.runWithDescriptor(CurrentTestDescriptor.java:17)
	at app//net.jqwik.engine.execution.pipeline.ExecutionTask$1.execute(ExecutionTask.java:31)
	at app//net.jqwik.engine.execution.pipeline.ExecutionPipeline.runToTermination(ExecutionPipeline.java:82)
	at app//net.jqwik.engine.execution.JqwikExecutor.execute(JqwikExecutor.java:46)
	at app//net.jqwik.engine.JqwikTestEngine.executeTests(JqwikTestEngine.java:70)
	at app//net.jqwik.engine.JqwikTestEngine.execute(JqwikTestEngine.java:53)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at app//org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base@11.0.15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.15/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.15/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

Manually produced stacktrace of the root-cause exception:
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.jqwik.engine.properties.arbitraries.DefaultTraverseArbitrary.lambda$combinatorForMethod$5(DefaultTraverseArbitrary.java:154)
	at net.jqwik.engine.properties.arbitraries.DefaultTraverseArbitrary.generateNext(DefaultTraverseArbitrary.java:165)
	at net.jqwik.engine.properties.arbitraries.DefaultTraverseArbitrary.lambda$combinatorForMethod$6(DefaultTraverseArbitrary.java:154)
	at net.jqwik.engine.properties.arbitraries.DefaultTraverseArbitrary.lambda$createArbitrary$2(DefaultTraverseArbitrary.java:116)
	at net.jqwik.api.Combinators$ListCombinator$1.lambda$edgeCases$3(Combinators.java:768)
	at net.jqwik.engine.properties.shrinking.CombinedShrinkable.createValue(CombinedShrinkable.java:25)
	at net.jqwik.engine.properties.shrinking.CombinedShrinkable.value(CombinedShrinkable.java:21)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.lambda$ignoreException$10(EdgeCasesSupport.java:120)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.ignoreException(EdgeCasesSupport.java:133)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$4.edgeCases(ArbitraryFacadeImpl.java:168)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.lambda$flatMapArbitrary$19(EdgeCasesSupport.java:153)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.flatMapArbitrary(EdgeCasesSupport.java:167)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.concatFrom(EdgeCasesSupport.java:58)
	at net.jqwik.engine.properties.arbitraries.OneOfArbitrary.edgeCases(OneOfArbitrary.java:51)
	at net.jqwik.api.arbitraries.ArbitraryDecorator.edgeCases(ArbitraryDecorator.java:57)
	at net.jqwik.engine.properties.arbitraries.EdgeCasesSupport.combine(EdgeCasesSupport.java:182)
	at net.jqwik.engine.facades.CombinatorsFacadeImpl.combineEdgeCases(CombinatorsFacadeImpl.java:37)
	at net.jqwik.api.Combinators$ListCombinator$1.edgeCases(Combinators.java:769)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl$4.edgeCases(ArbitraryFacadeImpl.java:168)
	at net.jqwik.api.arbitraries.ArbitraryDecorator.edgeCases(ArbitraryDecorator.java:57)
	at net.jqwik.api.arbitraries.ArbitraryDecorator.edgeCases(ArbitraryDecorator.java:57)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl.generator(ArbitraryFacadeImpl.java:232)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl.lambda$memoizedGenerator$0(ArbitraryFacadeImpl.java:226)
	at net.jqwik.engine.facades.Memoize.lambda$memoizedGenerator$1(Memoize.java:29)
	at net.jqwik.engine.facades.Memoize.computeIfAbsent(Memoize.java:44)
	at net.jqwik.engine.facades.Memoize.memoizedGenerator(Memoize.java:26)
	at net.jqwik.engine.facades.ArbitraryFacadeImpl.memoizedGenerator(ArbitraryFacadeImpl.java:226)
	at net.jqwik.api.Arbitrary.generator(Arbitrary.java:92)
	at net.jqwik.engine.properties.RandomizedParameterGenerator.getGenerator(RandomizedParameterGenerator.java:40)
	at net.jqwik.engine.properties.RandomizedParameterGenerator.selectGenerator(RandomizedParameterGenerator.java:36)
	at net.jqwik.engine.properties.RandomizedParameterGenerator.next(RandomizedParameterGenerator.java:24)
	at net.jqwik.engine.properties.PurelyRandomShrinkablesGenerator.lambda$generateNext$0(PurelyRandomShrinkablesGenerator.java:21)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.jqwik.engine.properties.PurelyRandomShrinkablesGenerator.generateNext(PurelyRandomShrinkablesGenerator.java:22)
	at net.jqwik.engine.properties.RandomizedShrinkablesGenerator.next(RandomizedShrinkablesGenerator.java:212)
	at net.jqwik.engine.properties.RandomizedShrinkablesGenerator.next(RandomizedShrinkablesGenerator.java:15)
	at net.jqwik.engine.execution.ResolvingParametersGenerator.next(ResolvingParametersGenerator.java:36)
	at net.jqwik.engine.execution.AfterFailureParametersGenerator.next(AfterFailureParametersGenerator.java:85)
	at net.jqwik.engine.properties.GenericProperty.check(GenericProperty.java:57)
	at net.jqwik.engine.execution.CheckedProperty.check(CheckedProperty.java:67)
	at net.jqwik.engine.execution.PropertyMethodExecutor.executeProperty(PropertyMethodExecutor.java:90)
	at net.jqwik.engine.execution.PropertyMethodExecutor.executeMethod(PropertyMethodExecutor.java:69)
	at net.jqwik.engine.execution.PropertyMethodExecutor.lambda$execute$0(PropertyMethodExecutor.java:49)
	at net.jqwik.api.lifecycle.AroundPropertyHook.lambda$static$0(AroundPropertyHook.java:46)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at net.jqwik.api.PropertyDefaults$PropertyDefaultsHook.aroundProperty(PropertyDefaults.java:91)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at net.jqwik.engine.hooks.lifecycle.PropertyLifecycleMethodsHook.aroundProperty(PropertyLifecycleMethodsHook.java:57)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at net.jqwik.engine.hooks.statistics.StatisticsHook.aroundProperty(StatisticsHook.java:37)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at net.jqwik.engine.hooks.lifecycle.AutoCloseableHook.aroundProperty(AutoCloseableHook.java:13)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at net.jqwik.engine.execution.PropertyMethodExecutor.execute(PropertyMethodExecutor.java:47)
	at net.jqwik.engine.execution.PropertyTaskCreator.executeTestMethod(PropertyTaskCreator.java:166)
	at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$1(PropertyTaskCreator.java:51)
	at net.jqwik.engine.execution.lifecycle.CurrentDomainContext.runWithContext(CurrentDomainContext.java:28)
	at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$2(PropertyTaskCreator.java:50)
	at net.jqwik.engine.execution.pipeline.ExecutionTask$1.lambda$execute$0(ExecutionTask.java:31)
	at net.jqwik.engine.execution.lifecycle.CurrentTestDescriptor.runWithDescriptor(CurrentTestDescriptor.java:17)
	at net.jqwik.engine.execution.pipeline.ExecutionTask$1.execute(ExecutionTask.java:31)
	at net.jqwik.engine.execution.pipeline.ExecutionPipeline.runToTermination(ExecutionPipeline.java:82)
	at net.jqwik.engine.execution.JqwikExecutor.execute(JqwikExecutor.java:46)
	at net.jqwik.engine.JqwikTestEngine.executeTests(JqwikTestEngine.java:70)
	at net.jqwik.engine.JqwikTestEngine.execute(JqwikTestEngine.java:53)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.base/java.util.UUID.fromString(UUID.java:215)
	... 126 more
```

Configuration:
* jqwik 1.6.5
* OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)
 
## Suggested Solution

1. Prefer registered Arbitraries when they exist over recursively applying reflection for `@UseType`
2. For this particular case: Provide a UUID arbitrary with jqwik

## Discussion
The second suggested solution is an enhancement, but I think the need for reproducible UUIDs is frequent enough and their construction is simple enough to justify including such an arbitrary with jqwik.

**Comment by jlink** [comment]
Actually it already should work as you suggest, if your arbitrary provider has the  appropriate priority: https://jqwik.net/docs/current/user-guide.html#arbitrary-provider-priority
UseTypeArbitraryProvider has a priority of 1, so everything above 1 is supposed to trump that. If that doesn’t work, it’s a bug.

**Comment by tmohme** [comment]
You're right, it works - even with the inherited priority of 0 (?).
I shot myself in the foot by having the `UuidArbitraryProvider` implemented in a different subproject without a dependency to its `testFixtures`.
Thanks for your support & sorry for the disruption.

**Comment by jlink** [comment]
Right, priority 0 also works. UseTypeArbitraryProvider is bound to UseType annotation, so there’s no conflict.
