### ISSUE TITLE
FloatRange for narrow range leads to exception due to implicit conversion

### ISSUE THREAD

**Issue by blairdye** [jlink/jqwik#47]
## Testing Problem

Running this test will lead to the following error after a few iterations

> `	@Property
	boolean scaledFloats(@ForAll @FloatRange(min = 2.01f, max = 2.03f) float value) {
		return value >= 2.01f && value <= 2.03f;
	}`

> `net.jqwik.api.JqwikException: Number <2.00> is outside allowed range 2.009999990463257..2.0299999713897705
	at net.jqwik.engine.properties.shrinking.ShrinkableBigDecimal.determineTarget(ShrinkableBigDecimal.java:49)
	at net.jqwik.engine.properties.shrinking.ShrinkableBigDecimal.<init>(ShrinkableBigDecimal.java:21)
	at net.jqwik.engine.properties.arbitraries.randomized.RandomDecimalGenerators.lambda$createBaseGenerator$2(RandomDecimalGenerators.java:58)
	at net.jqwik.engine.properties.arbitraries.randomized.RandomGenerators.lambda$withEdgeCases$10(RandomGenerators.java:220)
	at net.jqwik.api.RandomGenerator.lambda$map$0(RandomGenerator.java:43)
`

## Suggested Solution

Can be fixed by altering line 45 in DefaultFloatArbitrary:

`	private BigDecimal toBigDecimal(float value) {
		return new BigDecimal(""+value);
	}
`

## Discussion

This seems to be caused by the conversion to double that occurs in BigDecimal.valueOf. 

I'm happy to contribute a fix, I have a branch waiting to push :)

**Comment by jlink** [comment]
@blairdye Thank for the catch. I'm happy to take a pull request. I'd suggest a slightly different solution, though:

```
class DefaultFloatArbitrary...
	private BigDecimal toBigDecimal(float value) {
		return new BigDecimal(Float.toString(value));
	}
```
It's functionally the same, just a bit more obvious for my taste.

**Comment by jlink** [comment]
Fixed in https://github.com/jlink/jqwik/pull/48
