### ISSUE TITLE
Tests with failed setup do not fail gradle build

### ISSUE THREAD

**Issue by michailgames** [jlink/jqwik#58]
## Testing Problem

Given test like this:
```
package xxx;

import net.jqwik.api.Example;

class FailingConstructorTest {

    private final String testConfig;

    FailingConstructorTest() {
        testConfig = loadConfig();
    }

    @Example
    void alwaysPass() {
        // do nothing
    }

    private String loadConfig() {
        throw new IllegalStateException();
    }
}
```
When running jqwik tests with gradle from command line: `gradle test -i`,
the error is printed out:

```
xxx.FailingConstructorTest STANDARD_ERROR
    May 29, 2019 4:47:59 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
    WARNING: TestEngine with ID 'jqwik' failed to execute tests
    net.jqwik.api.JqwikException: Cannot create instance of class 'class xxx.FailingConstructorTest'. Maybe it has no default constructor?
        at net.jqwik.engine.execution.PropertyTaskCreator.createTestInstance(PropertyTaskCreator.java:46)
        at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$0(PropertyTaskCreator.java:16)
        at net.jqwik.engine.execution.pipeline.ExecutionTask$1.execute(ExecutionTask.java:24)
        at net.jqwik.engine.execution.pipeline.ExecutionPipeline.runToTermination(ExecutionPipeline.java:81)
        at net.jqwik.engine.execution.JqwikExecutor.execute(JqwikExecutor.java:46)
        at net.jqwik.engine.JqwikTestEngine.executeTests(JqwikTestEngine.java:93)
        at net.jqwik.engine.JqwikTestEngine.execute(JqwikTestEngine.java:82)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.lang.IllegalStateException
        at xxx.FailingConstructorTest.loadConfig(FailingConstructorTest.java:19)
        at xxx.FailingConstructorTest.<init>(FailingConstructorTest.java:10)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:453)
        at org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:428)
        at org.junit.platform.commons.support.ReflectionSupport.newInstance(ReflectionSupport.java:180)
        at net.jqwik.engine.support.JqwikReflectionSupport.newInstanceWithDefaultConstructor(JqwikReflectionSupport.java:69)
        at net.jqwik.engine.execution.PropertyTaskCreator.createTestInstance(PropertyTaskCreator.java:40)
        ... 40 more
```

but **the test is not reported as failed** and gradle build is finished as successful. This behavior seems to occur since version 1.0.0 (tested on 1.0.0, 1.1.2 and 1.1.4). 

When using jqwik version <= 0.9.3 (tested on 0.9.3, 0.9.0 and 0.8.6), the above test is reported as failed, causing gradle to fail correctly.

## Suggested Solution

Assuming that it is not a bug in gradle or some configuration issue at our side, this looks like a huge regression, as it causes broken builds to pass silently on CI.
I think the behavior from <=0.9.3 was correct and should be brought back.

**Comment by jlink** [comment]
Thanks for pointing that out. I'll have a look.

**Comment by jlink** [comment]
Fixed in https://github.com/jlink/jqwik/commit/67bd680322426bebb8c71d71a56a32ffa9ce6e90

Available in version 1.1.5-SNAPSHOT

**Comment by michailgames** [comment]
Thanks for the fix! Is there any planned date for 1.1.5 release?

**Comment by jlink** [comment]
I guess I’ll have time next weekend. 

Von meinem iPad gesendet

**Comment by jlink** [comment]
1.1.5 is available on maven central
